// Private Chat Actions
export const CREATE_PRIVATE_CHAT = "CREATE_PRIVATE_CHAT";
export const CREATE_PRIVATE_CHAT_SUCCESS = "CREATE_PRIVATE_CHAT_SUCCESS";
export const CREATE_PRIVATE_CHAT_ERROR = "CREATE_PRIVATE_CHAT_ERROR";

export const FIND_PRIVATE_CHAT = "FIND_PRIVATE_CHAT";
export const FIND_PRIVATE_CHAT_SUCCESS = "FIND_PRIVATE_CHAT_SUCCESS";
export const FIND_PRIVATE_CHAT_ERROR = "FIND_PRIVATE_CHAT_ERROR";

// Group Chat Actions
export const CREATE_GROUP_CHAT = "CREATE_GROUP_CHAT";
export const CREATE_GROUP_CHAT_SUCCESS = "CREATE_GROUP_CHAT_SUCCESS";
export const CREATE_GROUP_CHAT_ERROR = "CREATE_GROUP_CHAT_ERROR";

// Get Chats Actions
export const GET_USER_CHATS = "GET_USER_CHATS";
export const GET_USER_CHATS_SUCCESS = "GET_USER_CHATS_SUCCESS";
export const GET_USER_CHATS_ERROR = "GET_USER_CHATS_ERROR";

export const GET_USER_GROUP_CHATS = "GET_USER_GROUP_CHATS";
export const GET_USER_GROUP_CHATS_SUCCESS = "GET_USER_GROUP_CHATS_SUCCESS";
export const GET_USER_GROUP_CHATS_ERROR = "GET_USER_GROUP_CHATS_ERROR";

export const GET_USER_PRIVATE_CHATS = "GET_USER_PRIVATE_CHATS";
export const GET_USER_PRIVATE_CHATS_SUCCESS = "GET_USER_PRIVATE_CHATS_SUCCESS";
export const GET_USER_PRIVATE_CHATS_ERROR = "GET_USER_PRIVATE_CHATS_ERROR";

export const GET_ADMIN_CHATS = "GET_ADMIN_CHATS";
export const GET_ADMIN_CHATS_SUCCESS = "GET_ADMIN_CHATS_SUCCESS";
export const GET_ADMIN_CHATS_ERROR = "GET_ADMIN_CHATS_ERROR";

// Single Chat Actions
export const GET_CHAT_BY_ID = "GET_CHAT_BY_ID";
export const GET_CHAT_BY_ID_SUCCESS = "GET_CHAT_BY_ID_SUCCESS";
export const GET_CHAT_BY_ID_ERROR = "GET_CHAT_BY_ID_ERROR";

// Search Chat Actions
export const SEARCH_CHATS = "SEARCH_CHATS";
export const SEARCH_CHATS_SUCCESS = "SEARCH_CHATS_SUCCESS";
export const SEARCH_CHATS_ERROR = "SEARCH_CHATS_ERROR";

// Group Management Actions
export const ADD_USER_TO_GROUP = "ADD_USER_TO_GROUP";
export const ADD_USER_TO_GROUP_SUCCESS = "ADD_USER_TO_GROUP_SUCCESS";
export const ADD_USER_TO_GROUP_ERROR = "ADD_USER_TO_GROUP_ERROR";

export const REMOVE_USER_FROM_GROUP = "REMOVE_USER_FROM_GROUP";
export const REMOVE_USER_FROM_GROUP_SUCCESS = "REMOVE_USER_FROM_GROUP_SUCCESS";
export const REMOVE_USER_FROM_GROUP_ERROR = "REMOVE_USER_FROM_GROUP_ERROR";

export const UPDATE_GROUP_CHAT = "UPDATE_GROUP_CHAT";
export const UPDATE_GROUP_CHAT_SUCCESS = "UPDATE_GROUP_CHAT_SUCCESS";
export const UPDATE_GROUP_CHAT_ERROR = "UPDATE_GROUP_CHAT_ERROR";

export const DELETE_GROUP_CHAT = "DELETE_GROUP_CHAT";
export const DELETE_GROUP_CHAT_SUCCESS = "DELETE_GROUP_CHAT_SUCCESS";
export const DELETE_GROUP_CHAT_ERROR = "DELETE_GROUP_CHAT_ERROR";

export const LEAVE_GROUP = "LEAVE_GROUP";
export const LEAVE_GROUP_SUCCESS = "LEAVE_GROUP_SUCCESS";
export const LEAVE_GROUP_ERROR = "LEAVE_GROUP_ERROR";

// Admin Actions
export const MAKE_ADMIN = "MAKE_ADMIN";
export const MAKE_ADMIN_SUCCESS = "MAKE_ADMIN_SUCCESS";
export const MAKE_ADMIN_ERROR = "MAKE_ADMIN_ERROR";

export const REMOVE_ADMIN = "REMOVE_ADMIN";
export const REMOVE_ADMIN_SUCCESS = "REMOVE_ADMIN_SUCCESS";
export const REMOVE_ADMIN_ERROR = "REMOVE_ADMIN_ERROR";

// Chat Status Actions
export const MARK_CHAT_AS_READ = "MARK_CHAT_AS_READ";
export const MARK_CHAT_AS_READ_SUCCESS = "MARK_CHAT_AS_READ_SUCCESS";
export const MARK_CHAT_AS_READ_ERROR = "MARK_CHAT_AS_READ_ERROR";

export const GET_UNREAD_COUNT = "GET_UNREAD_COUNT";
export const GET_UNREAD_COUNT_SUCCESS = "GET_UNREAD_COUNT_SUCCESS";
export const GET_UNREAD_COUNT_ERROR = "GET_UNREAD_COUNT_ERROR";

// Permission Check Actions
export const CHECK_CHAT_ACCESS = "CHECK_CHAT_ACCESS";
export const CHECK_CHAT_ACCESS_SUCCESS = "CHECK_CHAT_ACCESS_SUCCESS";
export const CHECK_CHAT_ACCESS_ERROR = "CHECK_CHAT_ACCESS_ERROR";

export const CHECK_IS_ADMIN = "CHECK_IS_ADMIN";
export const CHECK_IS_ADMIN_SUCCESS = "CHECK_IS_ADMIN_SUCCESS";
export const CHECK_IS_ADMIN_ERROR = "CHECK_IS_ADMIN_ERROR";

export const CHECK_IS_OWNER = "CHECK_IS_OWNER";
export const CHECK_IS_OWNER_SUCCESS = "CHECK_IS_OWNER_SUCCESS";
export const CHECK_IS_OWNER_ERROR = "CHECK_IS_OWNER_ERROR";

// UI Actions
export const SET_ACTIVE_CHAT = "SET_ACTIVE_CHAT";
export const CLEAR_ACTIVE_CHAT = "CLEAR_ACTIVE_CHAT";
export const SET_CHAT_LOADING = "SET_CHAT_LOADING";
export const CLEAR_CHAT_ERROR = "CLEAR_CHAT_ERROR";

// Real-time Actions
export const CHAT_UPDATED = "CHAT_UPDATED";
export const USER_JOINED_CHAT = "USER_JOINED_CHAT";
export const USER_LEFT_CHAT = "USER_LEFT_CHAT";
export const CHAT_DELETED = "CHAT_DELETED";
