// Send Message Actions
export const SEND_MESSAGE = "SEND_MESSAGE";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_ERROR = "SEND_MESSAGE_ERROR";

// Get Messages Actions
export const GET_CHAT_MESSAGES = "GET_CHAT_MESSAGES";
export const GET_CHAT_MESSAGES_SUCCESS = "GET_CHAT_MESSAGES_SUCCESS";
export const GET_CHAT_MESSAGES_ERROR = "GET_CHAT_MESSAGES_ERROR";

export const GET_MESSAGE_BY_ID = "GET_MESSAGE_BY_ID";
export const GET_MESSAGE_BY_ID_SUCCESS = "GET_MESSAGE_BY_ID_SUCCESS";
export const GET_MESSAGE_BY_ID_ERROR = "GET_MESSAGE_BY_ID_ERROR";

export const GET_MESSAGES_SINCE = "GET_MESSAGES_SINCE";
export const GET_MESSAGES_SINCE_SUCCESS = "GET_MESSAGES_SINCE_SUCCESS";
export const GET_MESSAGES_SINCE_ERROR = "GET_MESSAGES_SINCE_ERROR";

export const GET_MESSAGE_COUNT = "GET_MESSAGE_COUNT";
export const GET_MESSAGE_COUNT_SUCCESS = "GET_MESSAGE_COUNT_SUCCESS";
export const GET_MESSAGE_COUNT_ERROR = "GET_MESSAGE_COUNT_ERROR";

// Message Management Actions
export const EDIT_MESSAGE = "EDIT_MESSAGE";
export const EDIT_MESSAGE_SUCCESS = "EDIT_MESSAGE_SUCCESS";
export const EDIT_MESSAGE_ERROR = "EDIT_MESSAGE_ERROR";

export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS";
export const DELETE_MESSAGE_ERROR = "DELETE_MESSAGE_ERROR";

export const DELETE_MESSAGE_FOR_ME = "DELETE_MESSAGE_FOR_ME";
export const DELETE_MESSAGE_FOR_ME_SUCCESS = "DELETE_MESSAGE_FOR_ME_SUCCESS";
export const DELETE_MESSAGE_FOR_ME_ERROR = "DELETE_MESSAGE_FOR_ME_ERROR";

export const FORWARD_MESSAGE = "FORWARD_MESSAGE";
export const FORWARD_MESSAGE_SUCCESS = "FORWARD_MESSAGE_SUCCESS";
export const FORWARD_MESSAGE_ERROR = "FORWARD_MESSAGE_ERROR";

// Search Messages Actions
export const SEARCH_MESSAGES_IN_CHAT = "SEARCH_MESSAGES_IN_CHAT";
export const SEARCH_MESSAGES_IN_CHAT_SUCCESS =
  "SEARCH_MESSAGES_IN_CHAT_SUCCESS";
export const SEARCH_MESSAGES_IN_CHAT_ERROR = "SEARCH_MESSAGES_IN_CHAT_ERROR";

// Message Status Actions (Chat-level, not individual message)
export const MARK_MESSAGE_AS_READ = "MARK_CHAT_AS_READ"; // Renamed for clarity
export const MARK_MESSAGE_AS_READ_SUCCESS = "MARK_CHAT_AS_READ_SUCCESS";
export const MARK_MESSAGE_AS_READ_ERROR = "MARK_CHAT_AS_READ_ERROR";

// Permission Check Actions
export const CHECK_CAN_EDIT_MESSAGE = "CHECK_CAN_EDIT_MESSAGE";
export const CHECK_CAN_EDIT_MESSAGE_SUCCESS = "CHECK_CAN_EDIT_MESSAGE_SUCCESS";
export const CHECK_CAN_EDIT_MESSAGE_ERROR = "CHECK_CAN_EDIT_MESSAGE_ERROR";

export const CHECK_CAN_DELETE_MESSAGE = "CHECK_CAN_DELETE_MESSAGE";
export const CHECK_CAN_DELETE_MESSAGE_SUCCESS =
  "CHECK_CAN_DELETE_MESSAGE_SUCCESS";
export const CHECK_CAN_DELETE_MESSAGE_ERROR = "CHECK_CAN_DELETE_MESSAGE_ERROR";

// UI Actions
export const SET_ACTIVE_MESSAGE = "SET_ACTIVE_MESSAGE";
export const CLEAR_ACTIVE_MESSAGE = "CLEAR_ACTIVE_MESSAGE";
export const SET_MESSAGE_LOADING = "SET_MESSAGE_LOADING";
export const CLEAR_MESSAGE_ERROR = "CLEAR_MESSAGE_ERROR";
export const CLEAR_SEARCH_RESULTS = "CLEAR_SEARCH_RESULTS";

// Real-time Actions
export const NEW_MESSAGE_RECEIVED = "NEW_MESSAGE_RECEIVED";
export const MESSAGE_UPDATED = "MESSAGE_UPDATED";
export const MESSAGE_DELETED = "MESSAGE_DELETED";
export const USER_TYPING = "USER_TYPING";
export const USER_STOPPED_TYPING = "USER_STOPPED_TYPING";

// Typing Actions
export const SET_TYPING_USERS = "SET_TYPING_USERS";
export const ADD_TYPING_USER = "ADD_TYPING_USER";
export const REMOVE_TYPING_USER = "REMOVE_TYPING_USER";

// Message Draft Actions (for saving unsent messages)
export const SET_MESSAGE_DRAFT = "SET_MESSAGE_DRAFT";
export const CLEAR_MESSAGE_DRAFT = "CLEAR_MESSAGE_DRAFT";

// File Upload Actions
export const UPLOAD_FILE = "UPLOAD_FILE";
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS";
export const UPLOAD_FILE_ERROR = "UPLOAD_FILE_ERROR";

// Optimistic UI Actions
export const ADD_OPTIMISTIC_MESSAGE = "ADD_OPTIMISTIC_MESSAGE";
export const MARK_MESSAGE_FAILED = "MARK_MESSAGE_FAILED";